apiVersion: v2
name: go-ratelimit
description: A Ratelimit Service Helm chart for Kubernetes
type: application
version: 0.1.15
appVersion: 1.5.0
dependencies:
- name: "redis-sharded"
  version: 0.1.0
  alias: "redish"
  repository: "@softonic-public"
