apiVersion: v2
name: go-ratelimit
description: A Ratelimit Service Helm chart for Kubernetes
type: application
version: 1.0.3
appVersion: 1.5.0
dependencies:
- name: "redis-sharded"
  version: 0.3.0
  alias: "redish"
  repository: "https://charts.softonic.io"
